# Generated by Django 4.0.3 on 2022-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
